/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppMoviesRouteImport } from './routes/_app/movies'
import { Route as AppListsRouteImport } from './routes/_app/lists'
import { Route as AppErrorRouteImport } from './routes/_app/error'
import { Route as AppDownloadsRouteImport } from './routes/_app/downloads'
import { Route as App404RouteImport } from './routes/_app/404'
import { Route as AppTvIndexRouteImport } from './routes/_app/tv/index'
import { Route as AppSettingsIndexerRouteImport } from './routes/_app/settings/indexer'
import { Route as AppTvIdIndexRouteImport } from './routes/_app/tv/$id.index'
import { Route as AppMoviesIdIndexRouteImport } from './routes/_app/movies/$id.index'
import { Route as AppDownloadsIdIndexRouteImport } from './routes/_app/downloads/$id.index'
import { Route as AppTvIdTorrentsRouteImport } from './routes/_app/tv/$id.torrents'
import { Route as AppMoviesIdTorrentsRouteImport } from './routes/_app/movies/$id.torrents'
import { Route as AppDownloadsIdPlayRouteImport } from './routes/_app/downloads/$id.play'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesRoute = AppMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => AppRoute,
} as any)
const AppListsRoute = AppListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AppRoute,
} as any)
const AppErrorRoute = AppErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadsRoute = AppDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AppRoute,
} as any)
const App404Route = App404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => AppRoute,
} as any)
const AppTvIndexRoute = AppTvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexerRoute = AppSettingsIndexerRouteImport.update({
  id: '/indexer',
  path: '/indexer',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppTvIdIndexRoute = AppTvIdIndexRouteImport.update({
  id: '/tv/$id/',
  path: '/tv/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesIdIndexRoute = AppMoviesIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => AppMoviesRoute,
} as any)
const AppDownloadsIdIndexRoute = AppDownloadsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => AppDownloadsRoute,
} as any)
const AppTvIdTorrentsRoute = AppTvIdTorrentsRouteImport.update({
  id: '/tv/$id/torrents',
  path: '/tv/$id/torrents',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesIdTorrentsRoute = AppMoviesIdTorrentsRouteImport.update({
  id: '/$id/torrents',
  path: '/$id/torrents',
  getParentRoute: () => AppMoviesRoute,
} as any)
const AppDownloadsIdPlayRoute = AppDownloadsIdPlayRouteImport.update({
  id: '/$id/play',
  path: '/$id/play',
  getParentRoute: () => AppDownloadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/404': typeof App404Route
  '/downloads': typeof AppDownloadsRouteWithChildren
  '/error': typeof AppErrorRoute
  '/lists': typeof AppListsRoute
  '/movies': typeof AppMoviesRouteWithChildren
  '/onboarding': typeof AppOnboardingRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/settings/indexer': typeof AppSettingsIndexerRoute
  '/tv': typeof AppTvIndexRoute
  '/downloads/$id/play': typeof AppDownloadsIdPlayRoute
  '/movies/$id/torrents': typeof AppMoviesIdTorrentsRoute
  '/tv/$id/torrents': typeof AppTvIdTorrentsRoute
  '/downloads/$id': typeof AppDownloadsIdIndexRoute
  '/movies/$id': typeof AppMoviesIdIndexRoute
  '/tv/$id': typeof AppTvIdIndexRoute
}
export interface FileRoutesByTo {
  '/404': typeof App404Route
  '/downloads': typeof AppDownloadsRouteWithChildren
  '/error': typeof AppErrorRoute
  '/lists': typeof AppListsRoute
  '/movies': typeof AppMoviesRouteWithChildren
  '/onboarding': typeof AppOnboardingRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/settings/indexer': typeof AppSettingsIndexerRoute
  '/tv': typeof AppTvIndexRoute
  '/downloads/$id/play': typeof AppDownloadsIdPlayRoute
  '/movies/$id/torrents': typeof AppMoviesIdTorrentsRoute
  '/tv/$id/torrents': typeof AppTvIdTorrentsRoute
  '/downloads/$id': typeof AppDownloadsIdIndexRoute
  '/movies/$id': typeof AppMoviesIdIndexRoute
  '/tv/$id': typeof AppTvIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/404': typeof App404Route
  '/_app/downloads': typeof AppDownloadsRouteWithChildren
  '/_app/error': typeof AppErrorRoute
  '/_app/lists': typeof AppListsRoute
  '/_app/movies': typeof AppMoviesRouteWithChildren
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/indexer': typeof AppSettingsIndexerRoute
  '/_app/tv/': typeof AppTvIndexRoute
  '/_app/downloads/$id/play': typeof AppDownloadsIdPlayRoute
  '/_app/movies/$id/torrents': typeof AppMoviesIdTorrentsRoute
  '/_app/tv/$id/torrents': typeof AppTvIdTorrentsRoute
  '/_app/downloads/$id/': typeof AppDownloadsIdIndexRoute
  '/_app/movies/$id/': typeof AppMoviesIdIndexRoute
  '/_app/tv/$id/': typeof AppTvIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/404'
    | '/downloads'
    | '/error'
    | '/lists'
    | '/movies'
    | '/onboarding'
    | '/search'
    | '/settings'
    | '/login'
    | '/signup'
    | '/'
    | '/settings/indexer'
    | '/tv'
    | '/downloads/$id/play'
    | '/movies/$id/torrents'
    | '/tv/$id/torrents'
    | '/downloads/$id'
    | '/movies/$id'
    | '/tv/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/404'
    | '/downloads'
    | '/error'
    | '/lists'
    | '/movies'
    | '/onboarding'
    | '/search'
    | '/settings'
    | '/login'
    | '/signup'
    | '/'
    | '/settings/indexer'
    | '/tv'
    | '/downloads/$id/play'
    | '/movies/$id/torrents'
    | '/tv/$id/torrents'
    | '/downloads/$id'
    | '/movies/$id'
    | '/tv/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/404'
    | '/_app/downloads'
    | '/_app/error'
    | '/_app/lists'
    | '/_app/movies'
    | '/_app/onboarding'
    | '/_app/search'
    | '/_app/settings'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/'
    | '/_app/settings/indexer'
    | '/_app/tv/'
    | '/_app/downloads/$id/play'
    | '/_app/movies/$id/torrents'
    | '/_app/tv/$id/torrents'
    | '/_app/downloads/$id/'
    | '/_app/movies/$id/'
    | '/_app/tv/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies': {
      id: '/_app/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof AppMoviesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists': {
      id: '/_app/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AppListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/error': {
      id: '/_app/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof AppErrorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/downloads': {
      id: '/_app/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AppDownloadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/404': {
      id: '/_app/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof App404RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tv/': {
      id: '/_app/tv/'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof AppTvIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/indexer': {
      id: '/_app/settings/indexer'
      path: '/indexer'
      fullPath: '/settings/indexer'
      preLoaderRoute: typeof AppSettingsIndexerRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/tv/$id/': {
      id: '/_app/tv/$id/'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof AppTvIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/$id/': {
      id: '/_app/movies/$id/'
      path: '/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof AppMoviesIdIndexRouteImport
      parentRoute: typeof AppMoviesRoute
    }
    '/_app/downloads/$id/': {
      id: '/_app/downloads/$id/'
      path: '/$id'
      fullPath: '/downloads/$id'
      preLoaderRoute: typeof AppDownloadsIdIndexRouteImport
      parentRoute: typeof AppDownloadsRoute
    }
    '/_app/tv/$id/torrents': {
      id: '/_app/tv/$id/torrents'
      path: '/tv/$id/torrents'
      fullPath: '/tv/$id/torrents'
      preLoaderRoute: typeof AppTvIdTorrentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/$id/torrents': {
      id: '/_app/movies/$id/torrents'
      path: '/$id/torrents'
      fullPath: '/movies/$id/torrents'
      preLoaderRoute: typeof AppMoviesIdTorrentsRouteImport
      parentRoute: typeof AppMoviesRoute
    }
    '/_app/downloads/$id/play': {
      id: '/_app/downloads/$id/play'
      path: '/$id/play'
      fullPath: '/downloads/$id/play'
      preLoaderRoute: typeof AppDownloadsIdPlayRouteImport
      parentRoute: typeof AppDownloadsRoute
    }
  }
}

interface AppDownloadsRouteChildren {
  AppDownloadsIdPlayRoute: typeof AppDownloadsIdPlayRoute
  AppDownloadsIdIndexRoute: typeof AppDownloadsIdIndexRoute
}

const AppDownloadsRouteChildren: AppDownloadsRouteChildren = {
  AppDownloadsIdPlayRoute: AppDownloadsIdPlayRoute,
  AppDownloadsIdIndexRoute: AppDownloadsIdIndexRoute,
}

const AppDownloadsRouteWithChildren = AppDownloadsRoute._addFileChildren(
  AppDownloadsRouteChildren,
)

interface AppMoviesRouteChildren {
  AppMoviesIdTorrentsRoute: typeof AppMoviesIdTorrentsRoute
  AppMoviesIdIndexRoute: typeof AppMoviesIdIndexRoute
}

const AppMoviesRouteChildren: AppMoviesRouteChildren = {
  AppMoviesIdTorrentsRoute: AppMoviesIdTorrentsRoute,
  AppMoviesIdIndexRoute: AppMoviesIdIndexRoute,
}

const AppMoviesRouteWithChildren = AppMoviesRoute._addFileChildren(
  AppMoviesRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsIndexerRoute: typeof AppSettingsIndexerRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsIndexerRoute: AppSettingsIndexerRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  App404Route: typeof App404Route
  AppDownloadsRoute: typeof AppDownloadsRouteWithChildren
  AppErrorRoute: typeof AppErrorRoute
  AppListsRoute: typeof AppListsRoute
  AppMoviesRoute: typeof AppMoviesRouteWithChildren
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppTvIndexRoute: typeof AppTvIndexRoute
  AppTvIdTorrentsRoute: typeof AppTvIdTorrentsRoute
  AppTvIdIndexRoute: typeof AppTvIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  App404Route: App404Route,
  AppDownloadsRoute: AppDownloadsRouteWithChildren,
  AppErrorRoute: AppErrorRoute,
  AppListsRoute: AppListsRoute,
  AppMoviesRoute: AppMoviesRouteWithChildren,
  AppOnboardingRoute: AppOnboardingRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppTvIndexRoute: AppTvIndexRoute,
  AppTvIdTorrentsRoute: AppTvIdTorrentsRoute,
  AppTvIdIndexRoute: AppTvIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
