/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppTvRouteImport } from './routes/_app.tv'
import { Route as AppTorrentRouteImport } from './routes/_app.torrent'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppServerRouteImport } from './routes/_app.server'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppMoviesIndexRouteImport } from './routes/_app.movies.index'
import { Route as AppMoviesMovieIdRouteImport } from './routes/_app.movies.$movieId'
import { Route as AppListsWatchListRouteImport } from './routes/_app.lists.watch-list'
import { Route as AppListsLikeRouteImport } from './routes/_app.lists.like'
import { Route as AppListsHistoryRouteImport } from './routes/_app.lists.history'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppTvRoute = AppTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AppRoute,
} as any)
const AppTorrentRoute = AppTorrentRouteImport.update({
  id: '/torrent',
  path: '/torrent',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServerRoute = AppServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesIndexRoute = AppMoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesMovieIdRoute = AppMoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => AppRoute,
} as any)
const AppListsWatchListRoute = AppListsWatchListRouteImport.update({
  id: '/lists/watch-list',
  path: '/lists/watch-list',
  getParentRoute: () => AppRoute,
} as any)
const AppListsLikeRoute = AppListsLikeRouteImport.update({
  id: '/lists/like',
  path: '/lists/like',
  getParentRoute: () => AppRoute,
} as any)
const AppListsHistoryRoute = AppListsHistoryRouteImport.update({
  id: '/lists/history',
  path: '/lists/history',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/search': typeof AppSearchRoute
  '/server': typeof AppServerRoute
  '/settings': typeof AppSettingsRoute
  '/torrent': typeof AppTorrentRoute
  '/tv': typeof AppTvRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/lists/history': typeof AppListsHistoryRoute
  '/lists/like': typeof AppListsLikeRoute
  '/lists/watch-list': typeof AppListsWatchListRoute
  '/movies/$movieId': typeof AppMoviesMovieIdRoute
  '/movies': typeof AppMoviesIndexRoute
}
export interface FileRoutesByTo {
  '/search': typeof AppSearchRoute
  '/server': typeof AppServerRoute
  '/settings': typeof AppSettingsRoute
  '/torrent': typeof AppTorrentRoute
  '/tv': typeof AppTvRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/lists/history': typeof AppListsHistoryRoute
  '/lists/like': typeof AppListsLikeRoute
  '/lists/watch-list': typeof AppListsWatchListRoute
  '/movies/$movieId': typeof AppMoviesMovieIdRoute
  '/movies': typeof AppMoviesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/search': typeof AppSearchRoute
  '/_app/server': typeof AppServerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/torrent': typeof AppTorrentRoute
  '/_app/tv': typeof AppTvRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/lists/history': typeof AppListsHistoryRoute
  '/_app/lists/like': typeof AppListsLikeRoute
  '/_app/lists/watch-list': typeof AppListsWatchListRoute
  '/_app/movies/$movieId': typeof AppMoviesMovieIdRoute
  '/_app/movies/': typeof AppMoviesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/search'
    | '/server'
    | '/settings'
    | '/torrent'
    | '/tv'
    | '/login'
    | '/signup'
    | '/'
    | '/lists/history'
    | '/lists/like'
    | '/lists/watch-list'
    | '/movies/$movieId'
    | '/movies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/search'
    | '/server'
    | '/settings'
    | '/torrent'
    | '/tv'
    | '/login'
    | '/signup'
    | '/'
    | '/lists/history'
    | '/lists/like'
    | '/lists/watch-list'
    | '/movies/$movieId'
    | '/movies'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/search'
    | '/_app/server'
    | '/_app/settings'
    | '/_app/torrent'
    | '/_app/tv'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/'
    | '/_app/lists/history'
    | '/_app/lists/like'
    | '/_app/lists/watch-list'
    | '/_app/movies/$movieId'
    | '/_app/movies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/tv': {
      id: '/_app/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof AppTvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/torrent': {
      id: '/_app/torrent'
      path: '/torrent'
      fullPath: '/torrent'
      preLoaderRoute: typeof AppTorrentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/server': {
      id: '/_app/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof AppServerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/': {
      id: '/_app/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof AppMoviesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/$movieId': {
      id: '/_app/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof AppMoviesMovieIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/watch-list': {
      id: '/_app/lists/watch-list'
      path: '/lists/watch-list'
      fullPath: '/lists/watch-list'
      preLoaderRoute: typeof AppListsWatchListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/like': {
      id: '/_app/lists/like'
      path: '/lists/like'
      fullPath: '/lists/like'
      preLoaderRoute: typeof AppListsLikeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/history': {
      id: '/_app/lists/history'
      path: '/lists/history'
      fullPath: '/lists/history'
      preLoaderRoute: typeof AppListsHistoryRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSearchRoute: typeof AppSearchRoute
  AppServerRoute: typeof AppServerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTorrentRoute: typeof AppTorrentRoute
  AppTvRoute: typeof AppTvRoute
  AppIndexRoute: typeof AppIndexRoute
  AppListsHistoryRoute: typeof AppListsHistoryRoute
  AppListsLikeRoute: typeof AppListsLikeRoute
  AppListsWatchListRoute: typeof AppListsWatchListRoute
  AppMoviesMovieIdRoute: typeof AppMoviesMovieIdRoute
  AppMoviesIndexRoute: typeof AppMoviesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSearchRoute: AppSearchRoute,
  AppServerRoute: AppServerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTorrentRoute: AppTorrentRoute,
  AppTvRoute: AppTvRoute,
  AppIndexRoute: AppIndexRoute,
  AppListsHistoryRoute: AppListsHistoryRoute,
  AppListsLikeRoute: AppListsLikeRoute,
  AppListsWatchListRoute: AppListsWatchListRoute,
  AppMoviesMovieIdRoute: AppMoviesMovieIdRoute,
  AppMoviesIndexRoute: AppMoviesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
