/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as R404RouteImport } from './routes/404'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppTvIndexRouteImport } from './routes/_app/tv/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppMoviesIndexRouteImport } from './routes/_app/movies/index'
import { Route as AppDownloadsIndexRouteImport } from './routes/_app/downloads/index'
import { Route as AppSettingsIndexerRouteImport } from './routes/_app/settings/indexer'
import { Route as AppListsWatchListRouteImport } from './routes/_app/lists/watch-list'
import { Route as AppListsLikeRouteImport } from './routes/_app/lists/like'
import { Route as AppListsHistoryRouteImport } from './routes/_app/lists/history'
import { Route as AppTvIdIndexRouteImport } from './routes/_app/tv/$id.index'
import { Route as AppMoviesIdIndexRouteImport } from './routes/_app/movies/$id.index'
import { Route as AppDownloadsIdIndexRouteImport } from './routes/_app/downloads/$id.index'
import { Route as AppTvIdTorrentsRouteImport } from './routes/_app/tv/$id.torrents'
import { Route as AppMoviesIdTorrentsRouteImport } from './routes/_app/movies/$id.torrents'
import { Route as AppDownloadsIdPlayRouteImport } from './routes/_app/downloads/$id.play'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppTvIndexRoute = AppTvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesIndexRoute = AppMoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadsIndexRoute = AppDownloadsIndexRouteImport.update({
  id: '/downloads/',
  path: '/downloads/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexerRoute = AppSettingsIndexerRouteImport.update({
  id: '/settings/indexer',
  path: '/settings/indexer',
  getParentRoute: () => AppRoute,
} as any)
const AppListsWatchListRoute = AppListsWatchListRouteImport.update({
  id: '/lists/watch-list',
  path: '/lists/watch-list',
  getParentRoute: () => AppRoute,
} as any)
const AppListsLikeRoute = AppListsLikeRouteImport.update({
  id: '/lists/like',
  path: '/lists/like',
  getParentRoute: () => AppRoute,
} as any)
const AppListsHistoryRoute = AppListsHistoryRouteImport.update({
  id: '/lists/history',
  path: '/lists/history',
  getParentRoute: () => AppRoute,
} as any)
const AppTvIdIndexRoute = AppTvIdIndexRouteImport.update({
  id: '/tv/$id/',
  path: '/tv/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesIdIndexRoute = AppMoviesIdIndexRouteImport.update({
  id: '/movies/$id/',
  path: '/movies/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadsIdIndexRoute = AppDownloadsIdIndexRouteImport.update({
  id: '/downloads/$id/',
  path: '/downloads/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppTvIdTorrentsRoute = AppTvIdTorrentsRouteImport.update({
  id: '/tv/$id/torrents',
  path: '/tv/$id/torrents',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesIdTorrentsRoute = AppMoviesIdTorrentsRouteImport.update({
  id: '/movies/$id/torrents',
  path: '/movies/$id/torrents',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadsIdPlayRoute = AppDownloadsIdPlayRouteImport.update({
  id: '/downloads/$id/play',
  path: '/downloads/$id/play',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/404': typeof R404Route
  '/search': typeof AppSearchRoute
  '/users': typeof AppUsersRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/lists/history': typeof AppListsHistoryRoute
  '/lists/like': typeof AppListsLikeRoute
  '/lists/watch-list': typeof AppListsWatchListRoute
  '/settings/indexer': typeof AppSettingsIndexerRoute
  '/downloads': typeof AppDownloadsIndexRoute
  '/movies': typeof AppMoviesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tv': typeof AppTvIndexRoute
  '/downloads/$id/play': typeof AppDownloadsIdPlayRoute
  '/movies/$id/torrents': typeof AppMoviesIdTorrentsRoute
  '/tv/$id/torrents': typeof AppTvIdTorrentsRoute
  '/downloads/$id': typeof AppDownloadsIdIndexRoute
  '/movies/$id': typeof AppMoviesIdIndexRoute
  '/tv/$id': typeof AppTvIdIndexRoute
}
export interface FileRoutesByTo {
  '/404': typeof R404Route
  '/search': typeof AppSearchRoute
  '/users': typeof AppUsersRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/lists/history': typeof AppListsHistoryRoute
  '/lists/like': typeof AppListsLikeRoute
  '/lists/watch-list': typeof AppListsWatchListRoute
  '/settings/indexer': typeof AppSettingsIndexerRoute
  '/downloads': typeof AppDownloadsIndexRoute
  '/movies': typeof AppMoviesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tv': typeof AppTvIndexRoute
  '/downloads/$id/play': typeof AppDownloadsIdPlayRoute
  '/movies/$id/torrents': typeof AppMoviesIdTorrentsRoute
  '/tv/$id/torrents': typeof AppTvIdTorrentsRoute
  '/downloads/$id': typeof AppDownloadsIdIndexRoute
  '/movies/$id': typeof AppMoviesIdIndexRoute
  '/tv/$id': typeof AppTvIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/404': typeof R404Route
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/search': typeof AppSearchRoute
  '/_app/users': typeof AppUsersRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/lists/history': typeof AppListsHistoryRoute
  '/_app/lists/like': typeof AppListsLikeRoute
  '/_app/lists/watch-list': typeof AppListsWatchListRoute
  '/_app/settings/indexer': typeof AppSettingsIndexerRoute
  '/_app/downloads/': typeof AppDownloadsIndexRoute
  '/_app/movies/': typeof AppMoviesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tv/': typeof AppTvIndexRoute
  '/_app/downloads/$id/play': typeof AppDownloadsIdPlayRoute
  '/_app/movies/$id/torrents': typeof AppMoviesIdTorrentsRoute
  '/_app/tv/$id/torrents': typeof AppTvIdTorrentsRoute
  '/_app/downloads/$id/': typeof AppDownloadsIdIndexRoute
  '/_app/movies/$id/': typeof AppMoviesIdIndexRoute
  '/_app/tv/$id/': typeof AppTvIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/404'
    | '/search'
    | '/users'
    | '/login'
    | '/signup'
    | '/'
    | '/lists/history'
    | '/lists/like'
    | '/lists/watch-list'
    | '/settings/indexer'
    | '/downloads'
    | '/movies'
    | '/settings'
    | '/tv'
    | '/downloads/$id/play'
    | '/movies/$id/torrents'
    | '/tv/$id/torrents'
    | '/downloads/$id'
    | '/movies/$id'
    | '/tv/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/404'
    | '/search'
    | '/users'
    | '/login'
    | '/signup'
    | '/'
    | '/lists/history'
    | '/lists/like'
    | '/lists/watch-list'
    | '/settings/indexer'
    | '/downloads'
    | '/movies'
    | '/settings'
    | '/tv'
    | '/downloads/$id/play'
    | '/movies/$id/torrents'
    | '/tv/$id/torrents'
    | '/downloads/$id'
    | '/movies/$id'
    | '/tv/$id'
  id:
    | '__root__'
    | '/404'
    | '/_app'
    | '/_auth'
    | '/_app/search'
    | '/_app/users'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/'
    | '/_app/lists/history'
    | '/_app/lists/like'
    | '/_app/lists/watch-list'
    | '/_app/settings/indexer'
    | '/_app/downloads/'
    | '/_app/movies/'
    | '/_app/settings/'
    | '/_app/tv/'
    | '/_app/downloads/$id/play'
    | '/_app/movies/$id/torrents'
    | '/_app/tv/$id/torrents'
    | '/_app/downloads/$id/'
    | '/_app/movies/$id/'
    | '/_app/tv/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R404Route: typeof R404Route
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tv/': {
      id: '/_app/tv/'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof AppTvIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/': {
      id: '/_app/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof AppMoviesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/downloads/': {
      id: '/_app/downloads/'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AppDownloadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/indexer': {
      id: '/_app/settings/indexer'
      path: '/settings/indexer'
      fullPath: '/settings/indexer'
      preLoaderRoute: typeof AppSettingsIndexerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/watch-list': {
      id: '/_app/lists/watch-list'
      path: '/lists/watch-list'
      fullPath: '/lists/watch-list'
      preLoaderRoute: typeof AppListsWatchListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/like': {
      id: '/_app/lists/like'
      path: '/lists/like'
      fullPath: '/lists/like'
      preLoaderRoute: typeof AppListsLikeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/history': {
      id: '/_app/lists/history'
      path: '/lists/history'
      fullPath: '/lists/history'
      preLoaderRoute: typeof AppListsHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tv/$id/': {
      id: '/_app/tv/$id/'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof AppTvIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/$id/': {
      id: '/_app/movies/$id/'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof AppMoviesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/downloads/$id/': {
      id: '/_app/downloads/$id/'
      path: '/downloads/$id'
      fullPath: '/downloads/$id'
      preLoaderRoute: typeof AppDownloadsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tv/$id/torrents': {
      id: '/_app/tv/$id/torrents'
      path: '/tv/$id/torrents'
      fullPath: '/tv/$id/torrents'
      preLoaderRoute: typeof AppTvIdTorrentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/$id/torrents': {
      id: '/_app/movies/$id/torrents'
      path: '/movies/$id/torrents'
      fullPath: '/movies/$id/torrents'
      preLoaderRoute: typeof AppMoviesIdTorrentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/downloads/$id/play': {
      id: '/_app/downloads/$id/play'
      path: '/downloads/$id/play'
      fullPath: '/downloads/$id/play'
      preLoaderRoute: typeof AppDownloadsIdPlayRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSearchRoute: typeof AppSearchRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppListsHistoryRoute: typeof AppListsHistoryRoute
  AppListsLikeRoute: typeof AppListsLikeRoute
  AppListsWatchListRoute: typeof AppListsWatchListRoute
  AppSettingsIndexerRoute: typeof AppSettingsIndexerRoute
  AppDownloadsIndexRoute: typeof AppDownloadsIndexRoute
  AppMoviesIndexRoute: typeof AppMoviesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTvIndexRoute: typeof AppTvIndexRoute
  AppDownloadsIdPlayRoute: typeof AppDownloadsIdPlayRoute
  AppMoviesIdTorrentsRoute: typeof AppMoviesIdTorrentsRoute
  AppTvIdTorrentsRoute: typeof AppTvIdTorrentsRoute
  AppDownloadsIdIndexRoute: typeof AppDownloadsIdIndexRoute
  AppMoviesIdIndexRoute: typeof AppMoviesIdIndexRoute
  AppTvIdIndexRoute: typeof AppTvIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSearchRoute: AppSearchRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppListsHistoryRoute: AppListsHistoryRoute,
  AppListsLikeRoute: AppListsLikeRoute,
  AppListsWatchListRoute: AppListsWatchListRoute,
  AppSettingsIndexerRoute: AppSettingsIndexerRoute,
  AppDownloadsIndexRoute: AppDownloadsIndexRoute,
  AppMoviesIndexRoute: AppMoviesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTvIndexRoute: AppTvIndexRoute,
  AppDownloadsIdPlayRoute: AppDownloadsIdPlayRoute,
  AppMoviesIdTorrentsRoute: AppMoviesIdTorrentsRoute,
  AppTvIdTorrentsRoute: AppTvIdTorrentsRoute,
  AppDownloadsIdIndexRoute: AppDownloadsIdIndexRoute,
  AppMoviesIdIndexRoute: AppMoviesIdIndexRoute,
  AppTvIdIndexRoute: AppTvIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R404Route: R404Route,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
